// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission12.Models;

namespace Mission12.Migrations
{
    [DbContext(typeof(TempleContext))]
    [Migration("20220325223444_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Mission12.Models.Time", b =>
                {
                    b.Property<int>("TimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Booked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeValue")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeID");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            TimeID = 1,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 AM"
                        },
                        new
                        {
                            TimeID = 2,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "9:00 AM"
                        },
                        new
                        {
                            TimeID = 3,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "10:00 AM"
                        },
                        new
                        {
                            TimeID = 4,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "11:00 AM"
                        },
                        new
                        {
                            TimeID = 5,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "12:00 PM"
                        },
                        new
                        {
                            TimeID = 6,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "1:00 PM"
                        },
                        new
                        {
                            TimeID = 7,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "2:00 PM"
                        },
                        new
                        {
                            TimeID = 8,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "3:00 PM"
                        },
                        new
                        {
                            TimeID = 9,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "4:00 PM"
                        },
                        new
                        {
                            TimeID = 10,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "5:00 PM"
                        },
                        new
                        {
                            TimeID = 11,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "6:00 PM"
                        },
                        new
                        {
                            TimeID = 12,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "7:00 PM"
                        },
                        new
                        {
                            TimeID = 13,
                            Booked = false,
                            Date = "3/23/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 PM"
                        },
                        new
                        {
                            TimeID = 14,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 AM"
                        },
                        new
                        {
                            TimeID = 15,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "9:00 AM"
                        },
                        new
                        {
                            TimeID = 16,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "10:00 AM"
                        },
                        new
                        {
                            TimeID = 17,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "11:00 AM"
                        },
                        new
                        {
                            TimeID = 18,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "12:00 PM"
                        },
                        new
                        {
                            TimeID = 19,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "1:00 PM"
                        },
                        new
                        {
                            TimeID = 20,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "2:00 PM"
                        },
                        new
                        {
                            TimeID = 21,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "3:00 PM"
                        },
                        new
                        {
                            TimeID = 22,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "4:00 PM"
                        },
                        new
                        {
                            TimeID = 23,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "5:00 PM"
                        },
                        new
                        {
                            TimeID = 24,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "6:00 PM"
                        },
                        new
                        {
                            TimeID = 25,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "7:00 PM"
                        },
                        new
                        {
                            TimeID = 26,
                            Booked = false,
                            Date = "3/24/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 PM"
                        },
                        new
                        {
                            TimeID = 27,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 AM"
                        },
                        new
                        {
                            TimeID = 28,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "9:00 AM"
                        },
                        new
                        {
                            TimeID = 29,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "10:00 AM"
                        },
                        new
                        {
                            TimeID = 30,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "11:00 AM"
                        },
                        new
                        {
                            TimeID = 31,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "12:00 PM"
                        },
                        new
                        {
                            TimeID = 32,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "1:00 PM"
                        },
                        new
                        {
                            TimeID = 33,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "2:00 PM"
                        },
                        new
                        {
                            TimeID = 34,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "3:00 PM"
                        },
                        new
                        {
                            TimeID = 35,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "4:00 PM"
                        },
                        new
                        {
                            TimeID = 36,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "5:00 PM"
                        },
                        new
                        {
                            TimeID = 37,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "6:00 PM"
                        },
                        new
                        {
                            TimeID = 38,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "7:00 PM"
                        },
                        new
                        {
                            TimeID = 39,
                            Booked = false,
                            Date = "3/25/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 PM"
                        },
                        new
                        {
                            TimeID = 40,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 AM"
                        },
                        new
                        {
                            TimeID = 41,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "9:00 AM"
                        },
                        new
                        {
                            TimeID = 42,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "10:00 AM"
                        },
                        new
                        {
                            TimeID = 43,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "11:00 AM"
                        },
                        new
                        {
                            TimeID = 44,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "12:00 PM"
                        },
                        new
                        {
                            TimeID = 45,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "1:00 PM"
                        },
                        new
                        {
                            TimeID = 46,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "2:00 PM"
                        },
                        new
                        {
                            TimeID = 47,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "3:00 PM"
                        },
                        new
                        {
                            TimeID = 48,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "4:00 PM"
                        },
                        new
                        {
                            TimeID = 49,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "5:00 PM"
                        },
                        new
                        {
                            TimeID = 50,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "6:00 PM"
                        },
                        new
                        {
                            TimeID = 51,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "7:00 PM"
                        },
                        new
                        {
                            TimeID = 52,
                            Booked = false,
                            Date = "3/26/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 PM"
                        },
                        new
                        {
                            TimeID = 53,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 AM"
                        },
                        new
                        {
                            TimeID = 54,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "9:00 AM"
                        },
                        new
                        {
                            TimeID = 55,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "10:00 AM"
                        },
                        new
                        {
                            TimeID = 56,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "11:00 AM"
                        },
                        new
                        {
                            TimeID = 57,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "12:00 PM"
                        },
                        new
                        {
                            TimeID = 58,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "1:00 PM"
                        },
                        new
                        {
                            TimeID = 59,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "2:00 PM"
                        },
                        new
                        {
                            TimeID = 60,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "3:00 PM"
                        },
                        new
                        {
                            TimeID = 61,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "4:00 PM"
                        },
                        new
                        {
                            TimeID = 62,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "5:00 PM"
                        },
                        new
                        {
                            TimeID = 63,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "6:00 PM"
                        },
                        new
                        {
                            TimeID = 64,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "7:00 PM"
                        },
                        new
                        {
                            TimeID = 65,
                            Booked = false,
                            Date = "3/27/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 PM"
                        },
                        new
                        {
                            TimeID = 66,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 AM"
                        },
                        new
                        {
                            TimeID = 67,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "9:00 AM"
                        },
                        new
                        {
                            TimeID = 68,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "10:00 AM"
                        },
                        new
                        {
                            TimeID = 69,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "11:00 AM"
                        },
                        new
                        {
                            TimeID = 70,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "12:00 PM"
                        },
                        new
                        {
                            TimeID = 71,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "1:00 PM"
                        },
                        new
                        {
                            TimeID = 72,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "2:00 PM"
                        },
                        new
                        {
                            TimeID = 73,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "3:00 PM"
                        },
                        new
                        {
                            TimeID = 74,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "4:00 PM"
                        },
                        new
                        {
                            TimeID = 75,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "5:00 PM"
                        },
                        new
                        {
                            TimeID = 76,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "6:00 PM"
                        },
                        new
                        {
                            TimeID = 77,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "7:00 PM"
                        },
                        new
                        {
                            TimeID = 78,
                            Booked = false,
                            Date = "3/28/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 PM"
                        },
                        new
                        {
                            TimeID = 79,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 AM"
                        },
                        new
                        {
                            TimeID = 80,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "9:00 AM"
                        },
                        new
                        {
                            TimeID = 81,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "10:00 AM"
                        },
                        new
                        {
                            TimeID = 82,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "11:00 AM"
                        },
                        new
                        {
                            TimeID = 83,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "12:00 PM"
                        },
                        new
                        {
                            TimeID = 84,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "1:00 PM"
                        },
                        new
                        {
                            TimeID = 85,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "2:00 PM"
                        },
                        new
                        {
                            TimeID = 86,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "3:00 PM"
                        },
                        new
                        {
                            TimeID = 87,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "4:00 PM"
                        },
                        new
                        {
                            TimeID = 88,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "5:00 PM"
                        },
                        new
                        {
                            TimeID = 89,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "6:00 PM"
                        },
                        new
                        {
                            TimeID = 90,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "7:00 PM"
                        },
                        new
                        {
                            TimeID = 91,
                            Booked = false,
                            Date = "3/29/2022",
                            GroupSize = 0,
                            TimeValue = "8:00 PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
