// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission12.Models;

namespace Mission12.Migrations
{
    [DbContext(typeof(TempleContext))]
    [Migration("20220323173907_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Mission12.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentID");

                    b.HasIndex("TimeID");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentID = 1,
                            Email = "Test@test.com",
                            GroupName = "Nathan's Party Group",
                            GroupSize = 1,
                            Phone = "911",
                            TimeID = 1
                        });
                });

            modelBuilder.Entity("Mission12.Models.Time", b =>
                {
                    b.Property<int>("TimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Booked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeValueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TimeID");

                    b.HasIndex("TimeValueId");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            TimeID = 1,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValueId = 3
                        });
                });

            modelBuilder.Entity("Mission12.Models.TimeValue", b =>
                {
                    b.Property<int>("TimeValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeValueName")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeValueId");

                    b.ToTable("TimeValue");

                    b.HasData(
                        new
                        {
                            TimeValueId = 1,
                            TimeValueName = "8:00 AM"
                        },
                        new
                        {
                            TimeValueId = 2,
                            TimeValueName = "9:00 AM"
                        },
                        new
                        {
                            TimeValueId = 3,
                            TimeValueName = "10:00 AM"
                        },
                        new
                        {
                            TimeValueId = 4,
                            TimeValueName = "11:00 AM"
                        },
                        new
                        {
                            TimeValueId = 5,
                            TimeValueName = "12:00 AM"
                        },
                        new
                        {
                            TimeValueId = 6,
                            TimeValueName = "1:00 PM"
                        },
                        new
                        {
                            TimeValueId = 7,
                            TimeValueName = "2:00 PM"
                        },
                        new
                        {
                            TimeValueId = 8,
                            TimeValueName = "3:00 PM"
                        },
                        new
                        {
                            TimeValueId = 9,
                            TimeValueName = "4:00 PM"
                        },
                        new
                        {
                            TimeValueId = 10,
                            TimeValueName = "5:00 PM"
                        },
                        new
                        {
                            TimeValueId = 11,
                            TimeValueName = "6:00 PM"
                        },
                        new
                        {
                            TimeValueId = 12,
                            TimeValueName = "7:00 PM"
                        },
                        new
                        {
                            TimeValueId = 13,
                            TimeValueName = "8:00 PM"
                        });
                });

            modelBuilder.Entity("Mission12.Models.Appointment", b =>
                {
                    b.HasOne("Mission12.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mission12.Models.Time", b =>
                {
                    b.HasOne("Mission12.Models.TimeValue", "TimeValue")
                        .WithMany()
                        .HasForeignKey("TimeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
