// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission12.Models;

namespace Mission12.Migrations
{
    [DbContext(typeof(TempleContext))]
    partial class TempleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Mission12.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppointmentID");

                    b.HasIndex("TimeID");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentID = 1,
                            Email = "Test@test.com",
                            GroupName = "Nathan's Party Group",
                            GroupSize = 1,
                            Phone = "911",
                            TimeID = 1
                        });
                });

            modelBuilder.Entity("Mission12.Models.Time", b =>
                {
                    b.Property<int>("TimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Booked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeValue")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeID");

                    b.ToTable("Times");

                    b.HasData(
                        new
                        {
                            TimeID = 1,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "8:00 AM"
                        },
                        new
                        {
                            TimeID = 2,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "9:00 AM"
                        },
                        new
                        {
                            TimeID = 3,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "10:00 AM"
                        },
                        new
                        {
                            TimeID = 4,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "11:00 AM"
                        },
                        new
                        {
                            TimeID = 5,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "12:00 PM"
                        },
                        new
                        {
                            TimeID = 6,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "1:00 PM"
                        },
                        new
                        {
                            TimeID = 7,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "2:00 PM"
                        },
                        new
                        {
                            TimeID = 8,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "3:00 PM"
                        },
                        new
                        {
                            TimeID = 9,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "4:00 PM"
                        },
                        new
                        {
                            TimeID = 10,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "5:00 PM"
                        },
                        new
                        {
                            TimeID = 11,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "6:00 PM"
                        },
                        new
                        {
                            TimeID = 12,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "7:00 PM"
                        },
                        new
                        {
                            TimeID = 13,
                            Booked = true,
                            Date = "3/23/2022",
                            TimeValue = "8:00 PM"
                        });
                });

            modelBuilder.Entity("Mission12.Models.Appointment", b =>
                {
                    b.HasOne("Mission12.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
